#_config.yml

title: "Max Hoffmann"
description: "Math and MathEducation | Research, Teaching, Outreach"
lang: en
url: "https://maxthematics.github.io"
baseurl: ""
remote_theme: "alshedivat/al-folio"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  publications:
    output: false