#_config.yml

title: "Max Hoffmann"
description: 'Math and MathEducation | Research, Teaching, Outreach'
lang: en
url: "https://maxthematics.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - about.md

minimal_mistakes_skin: "sunrise" 

author:
  name   : "Dr. Max Hoffmann"
  avatar : "/assets/images/profile.png" 
  bio    : "Math(ematics&#124;Education)+"
  location: "Paderborn University"
  email  : "max.hoffmann@math.upb.de"
  links:
    - label: "University Profile"
      icon: "fas fa-university"
      url: "https://www.uni-paderborn.de/person/32202"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/maxthematics"