#_config.yml

title: "Max Hoffmann"
description: "Math and MathEducation | Research, Teaching, Outreach"
lang: en
url: "https://maxthematics.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - about.md

minimal_mistakes_skin: default