#_config.yml

title: "Max Hoffmann"
description: "Math and MathEducation | Research, Teaching, Outreach"
lang: en
url: "https://maxthematics.github.io"
baseurl: ""
theme: minima

header_pages:
  - about.md